<a href="https://colab.research.google.com/github/amr-5017/pytorch/blob/main/Copy_of_intro_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2


4

In [ ]:
import torch
import numpy as np

#LISTS

In [ ]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

## NUMPY ARRAYS

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.64900835, 0.00172195, 0.98540679, 0.85851042],
       [0.23442891, 0.92981567, 0.53941118, 0.10023293],
       [0.22815223, 0.10456579, 0.54487423, 0.955298  ]])

# TENSORS

In [ ]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.9842, 0.7188, 0.6605, 0.7752],
        [0.8521, 0.0278, 0.0964, 0.9395],
        [0.7866, 0.4660, 0.7496, 0.1535]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6490, 0.0017, 0.9854, 0.8585],
        [0.2344, 0.9298, 0.5394, 0.1002],
        [0.2282, 0.1046, 0.5449, 0.9553]], dtype=torch.float64)

# TENSOR_OPS

In [ ]:
mytorch = torch.arange(10)
mytorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshape and view
mytorch = mytorch.reshape(2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#reshape if we dont know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(5,-1)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Tensor_Math

In [3]:
import torch
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
#addition of tensors
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])