<a href="https://colab.research.google.com/github/amr-5017/pytorch/blob/main/Copy_of_intro_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2


4

In [ ]:
import torch
import numpy as np

#LISTS

In [ ]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

## NUMPY ARRAYS

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.64900835, 0.00172195, 0.98540679, 0.85851042],
       [0.23442891, 0.92981567, 0.53941118, 0.10023293],
       [0.22815223, 0.10456579, 0.54487423, 0.955298  ]])

# TENSORS

In [ ]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.9842, 0.7188, 0.6605, 0.7752],
        [0.8521, 0.0278, 0.0964, 0.9395],
        [0.7866, 0.4660, 0.7496, 0.1535]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6490, 0.0017, 0.9854, 0.8585],
        [0.2344, 0.9298, 0.5394, 0.1002],
        [0.2282, 0.1046, 0.5449, 0.9553]], dtype=torch.float64)

# TENSOR_OPS

In [ ]:
mytorch = torch.arange(10)
mytorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshape and view
mytorch = mytorch.reshape(2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#reshape if we dont know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(5,-1)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Tensor_Math

In [3]:
import torch
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
#addition of tensors
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [5]:
torch.sub(tensor_b,tensor_a)


tensor([4, 4, 4, 4])

In [7]:
torch.mul(tensor_a, tensor_b)
# tensor multiplication

tensor([ 5, 12, 21, 32])

division is also in similar lines

remainder modulus is also similar to python using %

# Nueral networks

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as f

In [10]:
# create a model class that inherits nn.module
class Model(nn.Module):
  #input layer(4 features of the flower) -->
  #Hidden layer1(some number of nuerons) -->
  #H2(n) -->
  #output(3 classes of iris flowers)
  def __init__(self,in_features =4,h1=8,h2=9,out_features=3):
    super().__init__() #instantiates our.nn module
    self.fc1 = nn.Linear(in_features,h1)
    self.fc2 = nn.linear(h1,h2)
    self.out = nn.linear(h2,out_features)

  def forward(self,x):
    # relu = rectified linear unit
    x = f.relu(self.fc1(x))
    x = f.relu(self.fc2(x))
    x = self.out(x)

    return x

In [ ]:
# pick a manual seed for randomisation
torch.manual_seed(41)
#create an instance of model
model = Model()

In [11]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
my_df = pd.read_csv(url)
my_df.head() # gives only the first five


sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [17]:
#change last column from strings to integers
my_df['variety'] = my_df['variety'].replace('Setosa',0.0)
my_df['variety'] = my_df['variety'].replace('Versilcolor',1.0)
my_df['variety'] = my_df['variety'].replace('Virginica',2.0)
my_df

sepal.length  sepal.width  petal.length  petal.width variety
0             5.1          3.5           1.4          0.2     0.0
1             4.9          3.0           1.4          0.2     0.0
2             4.7          3.2           1.3          0.2     0.0
3             4.6          3.1           1.5          0.2     0.0
4             5.0          3.6           1.4          0.2     0.0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3     2.0
146           6.3          2.5           5.0          1.9     2.0
147           6.5          3.0           5.2          2.0     2.0
148           6.2          3.4           5.4          2.3     2.0
149           5.9          3.0           5.1          1.8     2.0

[150 rows x 5 columns]

In [19]:
# train, test and split
x = my_df.drop('variety',axis=1)
y = my_df['variety']

In [20]:
# convert these to numpy arrays
x = x.values
y = y.values

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
# train test split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state =41)

In [23]:
x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)

In [30]:
# convert y labels into tensor long
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.